Backend/seethio_live/seethio_live/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("userauthentication.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

Backend/seethio_live/userauthentication/urls.py
from django.urls import path
from userauthentication.views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetConfirmView
from userauthentication.forms import CustomSetPasswordForm

app_name = "userauthentication"
urlpatterns = [
    path("", index, name="index"),
    path("home", home, name="home"),
    path("verify_email/<str:uidb64>/", verify_email, name="verify_email"),
    path("signup/", register_view, name="signup"),
    path("sign_success/", sign_success, name="sign_success"),
    path("signin/", login_view, name="signin"),
    path("email_verification_complete/", email_verification_complete, name="email_verification_complete"),
    path("signout/", logout_view, name="signout"),
    path('resend_password_reset_email/', resend_password_reset_email, name='resend_password_reset_email'),
    path("password_reset/", password_reset_request, name="password_reset"),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
     path(
        'password_reset/confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            form_class=CustomSetPasswordForm
        ),
        name='password_reset_confirm',
    ),
    path(
        "password_reset_complete",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

Backend/seethio_live/templates/Html/Login/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    />
    <title>Log in</title>
  </head>
  <body>
    <main>
      <div class="left">
        <img src="{% static 'images/login_new.jpg' %}" alt="" />
      </div>
      <div class="right">
        <div class="content">
          <div class="logo-div">
            <img
              src="{% static 'images/seethio_logo.png' %}"
              alt=""
              style="width: 100%; height: 100%"
            />
          </div>
          <h1>Welcome!</h1>
          <h2>Login to your account</h2>
          {% if messages %} {% for message in messages %}
          <div id="alert" class="alert alert-{{message.tags}}">
            <strong>{{ message }}</strong>
          </div>
          {% endfor %} {% endif %}
          <script>
            setTimeout(() => {
              $("#alert").alert("close");
            }, 3000);
          </script>
          <form action="" method="post" id="myForm">
            {% csrf_token %}
            <div class="full-width">
              <label for="email">Email</label>
              <input
                name="email"
                type="email"
                id="email"
                placeholder="example@gmail.com"
                required
              />
            </div>
            <div class="full-width">
              <label for="password1">Password</label>
              <input
                name="password"
                type="password"
                id="password1"
                style="padding-left: 30px"
                placeholder="********"
                required
              />
              <i class="fa-regular fa-eye-slash" id="eye"></i>
            </div>
            <span
              ><a href="{% url 'userauthentication:password_reset' %}"
                >Forgot Password?</a
              ></span
            >
            <div class="terms">
              <input type="checkbox" id="terms" />
              <label for="check"
                >I have read and accepted SEETHIO <span>Terms</span> &
                <span>Policy</span>.</label
              >
            </div>

            <center><button type="submit" id="submit">log in</button></center>
          </form>

          <div class="horizontal">
            <img src="{% static 'images/horizontal.svg' %}" alt="" />
            <p>Or continue with</p>
            <img src="{% static 'images/horizontal.svg' %}" alt="" />
          </div>
          <div id="message"></div>
          <div class="other">
            <a href=""><img src="{% static 'images/google.svg' %}" alt="" /></a>
            <a href=""
              ><img src="{% static 'images/facebook.png' %}" alt=""
            /></a>
          </div>
          <p>
            Already have an account?
            <span
              ><a href="{% url 'userauthentication:signup' %}">Sign up</a></span
            >
          </p>
        </div>
      </div>
    </main>

    <script src="{% static 'js/login.js' %}"></script>
  </body>
</html>

Backend/seethio_live/templates/Html/Login/login2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/login2.css' %}" />
    <title>Log in</title>
  </head>
  <body>
    <main>
      <div class="left">
        <div class="img-div"></div>
      </div>
      <div class="right">
        <div class="content">
          <div class="logo">
            <img src="{% static 'images/seethio_logo.png' %}" alt="" />
          </div>
          <h3>Welcome</h3>
          <h4>Login to your account</h4>
          {% if messages %} {% for message in messages %}
          <div id="alert" class="alert alert-{{message.tags}}">
            <strong>{{ message }}</strong>
          </div>
          {% endfor %} {% endif %}
          <script>
            setTimeout(() => {
              $("#alert").alert("close");
            }, 2000);
          </script>
          <form action="" method="post" id="myForm">
            {% csrf_token %}
            <div class="full_width">
              <input
                type="email"
                name="email"
                id="email"
                placeholder="Email Address"
              />
              <input
                name="password"
                type="password"
                id="password1"
                style="padding-left: 30px"
                placeholder="********"
                required
              />
              <i class="fa-regular fa-eye-slash" id="eye"></i>
            </div>
            <a href="#popup1">
              <p>Forgot Password?</p>
            </a>
            <div class="checkbutton">
              <input type="checkbox" name="checkbox" id="terms" />

              <p>
                I have read and accepted SEETHIO
                <a href=""><span>Terms</span> $ <span>Policy</span></a>
              </p>
            </div>
            <input type="submit" class="btn" value="Login" />
          </form>
          <div id="message"></div>
          <div class="horizontal">
            <img src="{% static 'images/horizontal.svg' %}" alt="" />
            <p>Or</p>
            <img src="{% static 'images/horizontal.svg' %}" alt="" />
          </div>
          <div class="social">
            <a href=""><img src="{% static 'images/google.svg' %}" alt="" /></a>
            <a href=""
              ><img src="{% static 'images/facebook.png' %}" alt=""
            /></a>
          </div>

          <p id="account">
            Don't have an account?
            <span
              ><a href="{% url 'userauthentication:signup' %}">Sign Up</a></span
            >
          </p>
        </div>
      </div>
    </main>
    <!-- ellipse -->
    <div class="ellipse">
      <div class="green"></div>
      <div class="yellow"></div>
    </div>

    <!-- password reset successful popup -->
    <div id="popup4" class="overlay">
      <div class="popup">
        <div class="check">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="200"
            height="200"
            viewBox="0 0 200 200"
            fill="none"
          >
            <circle cx="100" cy="100" r="100" fill="white" />
            <path
              d="M138.973 50.0178C137.136 48.9958 135.116 48.3459 133.028 48.1052C130.94 47.8645 128.825 48.0378 126.804 48.6151C124.783 49.1924 122.896 50.1624 121.25 51.4697C119.604 52.777 118.232 54.3959 117.213 56.2338L87.5086 109.69L70.5086 92.6898C69.0327 91.1616 67.2671 89.9427 65.3151 89.1042C63.363 88.2656 61.2635 87.8242 59.139 87.8058C57.0146 87.7873 54.9077 88.1921 52.9413 88.9966C50.975 89.8011 49.1886 90.9892 47.6863 92.4915C46.184 93.9937 44.996 95.7802 44.1915 97.7465C43.387 99.7129 42.9821 101.82 43.0006 103.944C43.0191 106.069 43.4604 108.168 44.299 110.12C45.1375 112.072 46.3564 113.838 47.8846 115.314L79.8846 147.314C82.9086 150.346 86.9886 152.01 91.1966 152.01L93.4126 151.85C95.865 151.507 98.2043 150.599 100.246 149.198C102.288 147.798 103.977 145.942 105.181 143.778L145.181 71.7778C146.202 69.9414 146.851 67.9218 147.092 65.8344C147.333 63.747 147.16 61.6326 146.583 59.612C146.007 57.5914 145.038 55.7041 143.732 54.0579C142.426 52.4117 140.809 51.0389 138.973 50.0178Z"
              fill="#006167"
            />
          </svg>
        </div>
        <a class="close" href="#">&times;</a>
        <div class="content_success">
          <h3>Password Reset Successful</h3>
          <button
            type="submit"
            onclick="window.location.href='../Html/login.html'"
          >
            Log in
          </button>
        </div>
      </div>
    </div>
    {% comment %}
    <script src="{% static 'js/login2.js' %}"></script>
    {% endcomment %} {% comment %}
    <script src="{% static 'js/password2.js' %}"></script>
    {% endcomment %}
  </body>
</html>